### ISSUE TITLE
No_key

### ISSUE THREAD

**Issue by milan-007** [oviradoi/FsMega#11] opened 2023-04-29 11:01 UTC
Just tried MegaFS, works great. But one folder has NO_KEY instead of its name, and everything stored in it, including subfolders and their contents, has the name NO_KEY.
Am I doing something wrong or is it a bug?

here are screenschots from android, lin browser Firefox and mega addon TC :
https://mega.nz/folder/FJMTRJJL#xP95nVHJn4dd9LsueN7j9Q

**Comment by milan-007** [comment] 2023-05-16 06:05
Hi, I found out, that NO_KEY filename/dirname is set  only for items that are copied / shared etc.

**Comment by oviradoi** [comment] 2023-05-16 07:33
I have searched for what could cause the NO_KEY folder, and it could be a one of a few causes: https://reddit.com/r/MEGA/comments/11u4v68/temporary_solution_for_those_having_undecrypted/

Because you can access the folder on the official Mega app, I think this is caused by the FsMega plugin using an older version of the Mega SDK.

When I get some time, I will release a new version of the plugin that uses the newest version of the Mega SDK to check if this problem will be fixed.

**Comment by milan-007** [comment] 2023-05-16 11:25
Thanks, I will wait :))

**Comment by oviradoi** [comment] 2023-05-24 17:55
I have released a new version of the plugin that uses the latest Mega SDK version.

Please try it out and let me know if it fixes the issue.

**Comment by milan-007** [comment] 2023-05-25 06:47
As I'm on holydays now, I tested it quickly. All files / dirs looks good now. tested on fresh TC / W7 . Super work, thanks... 
When I return to home, will test regullary and wrote to you, if some errors occurs.

**Closed** 2023-06-12 18:30 UTC
